chemins:
  dossier_data: data/
  dossier_resultats: output/

data_cols:
  annee: "annee"
  mois: "mois"
  clean_name: "clean_name"
  orderDate: "orderDate"
  plateforme: "plateforme"
  productName: "productName"
  productType: "productType"
  orderQuantity: "orderQuantity"
  productIsOrganic: "productIsOrganic"
  orderProductPrice: "orderProductPrice"
  productConditioningUnit: "productConditioningUnit"
  productConditioningQuantity: "productConditioningQuantity"

extension_fichier:
  extension: "\\.(csv|txt|xlsx)$"
